# Site settings
title: Wanglinzhizhi 
email: wanglinzhizhi@gmail.com
description: "游走在上下文无关文法间"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://wagnlinzh.github.io"
twitter_username: wanglinzhizhi
github_username:  wagnlinzh
facebook_username:  wanglinzhizhi

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
