# Site settings
title: Wanglinzhizhi's Blog
email: wanglinzhizhi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  万有引力的作用下，每个人的时间是相对的
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: wanglinzhizhi
github_username:  wagnlinzh


permalink:           pretty
relative_permalinks: true

# Setup
title:               Wanglinzhizhi's Blog
tagline:             游走在上下文无关文法间  #副标题
#description:         游走在上下文无关文法间
paginate:            10

# About/contact
# author:
#  name:              wanglinzhizhi
#  url:               "http://yourdomain.com"
#  email:             wanglinzhizhi@gmail.com

# Custom vars
version:             0.1.0